src/main/java/com/mycompany/model/Post.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * @author RENT
 */
@Entity
@Table
public class Post {
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Integer id;
    @Column
    private String user;
    @Column
    private String title;
    @Column
    private String text;

    
    public void setUser(String user) {
        this.user = user;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getUser() {
        return user;
    }

    public String getTitle() {
        return title;
    }

    public String getText() {
        return text;
    }
    
}

src/main/java/com/mycompany/NewJSFManagedBean.java
package com.mycompany;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.mycompany.model.Post;
import java.util.List;
import javax.faces.bean.ApplicationScoped;

import javax.faces.bean.ManagedBean;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.persistence.*;

/**
 *
 * @author RENT
 */
@ManagedBean(name = "applicationController")
@ApplicationScoped
public class NewJSFManagedBean {

    private final EntityManagerFactory emf;
    private final EntityManager em;

    private String version = "60beta";

    public void setVersion(String version) {
        this.version = version;
    }

    public String getVersion() {
        return version;
    }

    /**
     * Creates a new instance of NewJSFManagedBean
     */
    public NewJSFManagedBean() {
        emf = Persistence.createEntityManagerFactory("pu");  //powiązanie z bazą danych poprzez powiedzenie fabryce, by zrobiła entty managera
        em = emf.createEntityManager();

    }

    public EntityManager getEntityManager() {
        return em;
    }
    
    public List<Post> getList() {
        Query query = em.createQuery("FROM Post");
        return query.getResultList();
    }


}

src/main/java/com/mycompany/controller/SessionController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.controller;

import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;

/**
 *
 * @author RENT
 */
@Named(value = "sessionController")
@SessionScoped
public class SessionController implements Serializable {
    private Integer counter = 0;

    public void setCounter(Integer counter) {
        this.counter = counter++;
    }

    public Integer getCounter() {
        return counter;
    }
    

    /**
     * Creates a new instance of SessionController
     */
    public SessionController() {
        counter++;
        
    }
    
    
    
}

src/main/webapp/about_me.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <head>
        <title>TODO supply a title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body>
        <div>I am round. I am cookie!</div>
    </body>
</html>

src/main/webapp/guestbook.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <head>
        <title>TODO supply a title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body>
        <div>Hello!!</div>
        <h:dataTable value="#{applicationController.list}" var="post">
            <h:column>
                <f:facet name="header">User</f:facet>
                #{post.user}
            </h:column>
            <h:column>
                <f:facet name="header">Title</f:facet>
                #{post.title}
            </h:column>
            <h:column>
                <f:facet name="header">Text</f:facet>
                #{post.text}
            </h:column>
        </h:dataTable>
        
        <h:form>
            <h:inputText value="#{formguest.user}"></h:inputText>
            <h:inputText value="#{formguest.title}"></h:inputText>
            <h:inputText value="#{formguest.text}"></h:inputText>
            <h:commandButton action="#{formguest.save}" value="Save"/>
        </h:form>
    </body>
</html>

src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h:panelGrid>
        <h:form>
            <h:commandLink action='faces/guestbook.xhtml'>Guestbook</h:commandLink><br/>
            <h:commandLink action='faces/about_me'>About me</h:commandLink><br/>
          
        </h:form>
        </h:panelGrid>
        <h:dataTable>
            
           
        </h:dataTable>
        
        <h:outputText value="#{applicationController.version}"/>
        
        Hello from Facelets
        <div>
            <h:outputText value="You are: "></h:outputText>
        <h:outputText value="#{sessionController.counter}"/>
        <h:outputText value=" visitor"></h:outputText>
        </div>
    </h:body>
</html>